apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-server-deployment
  labels:
    app: keycloak-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-server
  template:
    metadata:
      labels:
        app: keycloak-server
    spec:
      containers:
        - name: keycloak-server
          image: quay.io/keycloak/keycloak:23.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: keycloak
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: keycloak-configuration
          env:
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: KEYCLOAK_ADMIN_PASSWORD
          args: [ "start-dev" ]






