apiVersion: v1
kind: Service
metadata:
  name: keycloak-server-service
  labels:
    app: keycloak-server
spec:
  type: NodePort
  ports:
    - name: keycloak
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31001
  selector:
    app: keycloak-server

