apiVersion: v1
kind: Service
metadata:
  name: keycloak-app-service
  labels:
    app: keycloak-service
spec:
  type: NodePort
  ports:
    - name: keycloak
      port: 8082
      protocol: TCP
      targetPort: 8082
      nodePort: 31600
  selector:
    app: keycloak-service