apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres-service
spec:
  type: NodePort
  selector:
    app: keycloak-postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32100